'''
Created on Sep 29, 2013

@author: Alan

Takes as input the {0}_summary.txt file generated by an OpinionPropagation.py experiment.
Calculates a {0}_dev.txt output file that contains a (tab delimited) matrix, containing the 
average amount of deviation from 0.5, for each category of the experiment. 
'''
#import fileinput
import re
import sys

INPUT_DIR = "D:\\EclipseWorkspace\\\OpinionPropagation\\opinion_prop\\safehouse\\"
INPUT_EXPR = sys.argv[1]
INPUT_SUFFIX = "_summary.txt"
OUTPUT_SUFFIX = "_devi.txt"
INPUT_FILE = INPUT_DIR + INPUT_EXPR + INPUT_SUFFIX
OUTPUT_FILE = INPUT_DIR + INPUT_EXPR + OUTPUT_SUFFIX

filein = open(INPUT_FILE,'r')

curr_m = None
curr_e = None
tally = 100.0
denom = -100

for line in filein:
    if re.match("^[^\t]*\t[^\t]*\t[^\t]*\t([^\t])*\t([^\t])*\t",line):
        words = re.split("\t", line)
        if words[0] == "nVertices":
            continue
        m = words[3]
        e = words[4]
        devi = float(words[10])
        #print ("> {0} {1} {2}".format(m,e,devi))
        if curr_m == None:
            curr_m = m
            curr_e = e
            tally = 0
            denom = 0
        elif curr_m != m:
            print('{0}\n'.format(tally/denom),end='')
            curr_m = m
            curr_e = e
            tally = 0
            denom = 0
        elif curr_e != e:
            print('{0}\t'.format(tally/denom),end='')
            curr_e = e
            tally = 0
            denom = 0
        
        tally += devi
        denom += 1
    else:
        print ("NO MATCH : {0}".format(line))
print('{0}\n'.format(tally/denom),end='')
